// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJYpqvRZibbAWfHW7PDlxTV8f5mHvIkcM',
    appId: '1:135235027317:web:705acdc00a2b1e448d133c',
    messagingSenderId: '135235027317',
    projectId: 'fooddeliveryapp-8b9c0',
    authDomain: 'fooddeliveryapp-8b9c0.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-8b9c0.appspot.com',
    measurementId: 'G-XTGW85VXTJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASLx9lIdO-gFc5bcvS_l3dP7CXr-1nX6E',
    appId: '1:135235027317:android:0f80dd38856182028d133c',
    messagingSenderId: '135235027317',
    projectId: 'fooddeliveryapp-8b9c0',
    storageBucket: 'fooddeliveryapp-8b9c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVvYCOt2eM_2ZYkqK0M7fBJnRknHWINXg',
    appId: '1:135235027317:ios:53122217501adf5b8d133c',
    messagingSenderId: '135235027317',
    projectId: 'fooddeliveryapp-8b9c0',
    storageBucket: 'fooddeliveryapp-8b9c0.appspot.com',
    iosClientId: '135235027317-hi629j847b3opn8dklbs2cmaa81g4cd2.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVvYCOt2eM_2ZYkqK0M7fBJnRknHWINXg',
    appId: '1:135235027317:ios:53122217501adf5b8d133c',
    messagingSenderId: '135235027317',
    projectId: 'fooddeliveryapp-8b9c0',
    storageBucket: 'fooddeliveryapp-8b9c0.appspot.com',
    iosClientId: '135235027317-hi629j847b3opn8dklbs2cmaa81g4cd2.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodDelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJYpqvRZibbAWfHW7PDlxTV8f5mHvIkcM',
    appId: '1:135235027317:web:ef2b1890bf8dd20c8d133c',
    messagingSenderId: '135235027317',
    projectId: 'fooddeliveryapp-8b9c0',
    authDomain: 'fooddeliveryapp-8b9c0.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-8b9c0.appspot.com',
    measurementId: 'G-LP43VPZ025',
  );
}
